<?php
require __DIR__ . '/lib/bootstrap.php';

if (!aib_agent_auth()) {
    aib_json_response([
        'ok' => false,
        'error' => 'invalid_or_missing_token',
        'hint' => 'Open the exact Agent URL generated by manage.php, or send X-AIB-Token / Authorization: Bearer.',
    ], 401);
}

$config = aib_config();
$in = aib_input();
$action = (string)($in['action'] ?? 'inbox');
$agentName = aib_clean_message((string)($in['agent_name'] ?? 'External AI Agent'), 120);
aib_touch_agent($agentName ?: 'External AI Agent');
$token = (string)$config['agent_token'];

function agent_wait_url(string $token, int $wait = 20): string {
    return aib_url('agent.php', ['token'=>$token,'action'=>'inbox','wait'=>$wait,'claim'=>1]);
}

if ($action === 'heartbeat') {
    $state = aib_clean_message((string)($in['state'] ?? 'idle'), 80);
    $model = aib_clean_message((string)($in['model'] ?? ''), 160);
    $modelId = aib_clean_message((string)($in['model_id'] ?? ''), 100);
    $version = aib_clean_message((string)($in['version'] ?? ''), 80);
    $activeId = aib_clean_message((string)($in['message_id'] ?? ''), 80);
    $models = aib_public_models($in['models'] ?? []);
    $modelReady = !empty($in['model_ready']);
    $modelLoading = !empty($in['model_loading']);
    if (isset($in['control_result']) && is_array($in['control_result'])) {
        aib_update_model_control_result($in['control_result']);
    }
    $control = aib_model_control();
    if ($modelReady && $modelId !== '' && ($control['model_id'] ?? '') === $modelId && in_array(($control['status'] ?? ''), ['pending','loading'], true)) {
        $control['status'] = 'ready';
        $control['error'] = null;
        $control['updated_at'] = aib_now();
        $control['model_name'] = $model ?: ($control['model_name'] ?? null);
        aib_atomic_write(aib_model_control_path(), json_encode($control, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));
    }
    aib_touch_agent($agentName ?: 'External AI Agent', [
        'state'=>$state ?: 'idle',
        'model'=>$model ?: null,
        'model_id'=>$modelId ?: null,
        'model_ready'=>$modelReady,
        'model_loading'=>$modelLoading,
        'models'=>$models,
        'version'=>$version ?: null,
        'active_message_id'=>$activeId ?: null,
    ]);
    $control = aib_model_control();
    $modelRequest = null;
    if (($control['status'] ?? '') === 'pending' && !empty($control['request_id'])) {
        $actionName = (string)($control['action'] ?? 'load');
        if ($actionName === 'unload' || !empty($control['model_id'])) {
            $modelRequest = ['request_id'=>$control['request_id'],'action'=>$actionName,'model_id'=>(string)($control['model_id'] ?? '')];
        }
        $control['status'] = 'loading';
        $control['updated_at'] = aib_now();
        aib_atomic_write(aib_model_control_path(), json_encode($control, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));
    }
    aib_json_response([
        'ok'=>true,
        'state'=>'alive',
        'agent'=>aib_agent_status(),
        'model_request'=>$modelRequest,
        'instruction'=>'Continue the agent loop. Request next_wait_url immediately.',
        'next_wait_url'=>agent_wait_url($token, (int)$config['agent_long_poll_seconds']),
        'server_time'=>aib_now(),
    ]);
}

// LlamaForge/site-sync live activity endpoint. Each event is persisted with the message
// so the public chat can show what the local Agent is doing in real time.
if ($action === 'activity' && in_array($_SERVER['REQUEST_METHOD'], ['POST','GET'], true)) {
    $id = trim((string)($in['message_id'] ?? ''));
    if (!aib_is_uuid($id)) aib_json_response(['ok'=>false,'error'=>'invalid_message_id'], 400);
    $event = $in['event'] ?? null;
    if (is_string($event)) {
        $decoded = json_decode($event, true);
        $event = is_array($decoded) ? $decoded : ['label'=>$event];
    }
    if (!is_array($event)) {
        $event = [
            'type'=>(string)($in['type'] ?? 'progress'),
            'phase'=>(string)($in['phase'] ?? ''),
            'label'=>(string)($in['label'] ?? ''),
            'detail'=>(string)($in['detail'] ?? ''),
            'skill'=>(string)($in['skill'] ?? ''),
            'status'=>(string)($in['status'] ?? ''),
        ];
    }
    $visible = !isset($in['visible']) || !in_array(strtolower((string)$in['visible']), ['0','false','no'], true);
    $updated = aib_append_activity($id, $event, $agentName ?: 'LlamaForge', $visible);
    if (!$updated) aib_json_response(['ok'=>false,'error'=>'message_not_found'], 404);
    aib_touch_agent($agentName ?: 'LlamaForge', [
        'state'=>'working',
        'active_message_id'=>$id,
        'model'=>aib_clean_message((string)($in['model'] ?? ''),160) ?: null,
        'version'=>aib_clean_message((string)($in['version'] ?? ''),80) ?: null,
    ]);
    aib_json_response(['ok'=>true,'message_id'=>$id,'activity_count'=>count($updated['activity'] ?? []),'cancel_requested'=>!empty($updated['cancel_requested']) || ($updated['status'] ?? '') === 'cancelled','server_time'=>aib_now()]);
}

// Standard token-authenticated live progress endpoint for capable API agents.
if ($action === 'typing' && in_array($_SERVER['REQUEST_METHOD'], ['POST','GET'], true)) {
    $id = trim((string)($in['message_id'] ?? ''));
    $partial = aib_clean_message((string)($in['partial_answer'] ?? ''), (int)($config['max_answer_chars'] ?? 50000));
    $updated = aib_update_message($id, function($row) use ($partial, $agentName) {
        if (in_array(($row['status'] ?? ''), ['answered','cancelled'], true)) return $row;
        $row['status'] = 'processing';
        $row['claimed_at'] = aib_now();
        $row['agent_name'] = $agentName ?: 'External AI Agent';
        if ($partial !== '') $row['partial_answer'] = $partial;
        return $row;
    });
    if (!$updated) aib_json_response(['ok'=>false,'error'=>'message_not_found'],404);
    aib_json_response([
        'ok'=>true,
        'message_id'=>$id,
        'status'=>$updated['status'],
        'cancel_requested'=>!empty($updated['cancel_requested']) || ($updated['status'] ?? '') === 'cancelled',
        'instruction'=>'Continue composing. When finished, submit action=reply.',
    ]);
}

// Standard token-authenticated reply endpoint for API-capable agents.
if ($action === 'reply' && in_array($_SERVER['REQUEST_METHOD'], ['POST','GET'], true)) {
    if ($_SERVER['REQUEST_METHOD'] === 'GET' && empty($config['browser_get_reply'])) {
        aib_json_response(['ok'=>false,'error'=>'get_reply_disabled','hint'=>'Use POST JSON or the scoped web_get_action supplied with each pending message.'],405);
    }
    $id = trim((string)($in['message_id'] ?? ''));
    $answer = aib_clean_message((string)($in['answer'] ?? ''), (int)($config['max_answer_chars'] ?? 50000));
    if (!aib_is_uuid($id) || $answer === '') aib_json_response(['ok'=>false,'error'=>'message_id_and_answer_required'],400);
    $updated = aib_update_message($id, function($row) use ($answer, $agentName) {
        if (($row['status'] ?? '') === 'cancelled' || !empty($row['cancel_requested'])) return $row;
        $row['answer'] = $answer;
        $row['partial_answer'] = null;
        $row['status'] = 'answered';
        $row['agent_name'] = $agentName ?: 'External AI Agent';
        $row['answered_at'] = aib_now();
        $events = is_array($row['activity'] ?? null) ? $row['activity'] : [];
        $events[] = aib_activity_event(['type'=>'complete','phase'=>'complete','label'=>'پاسخ نهایی آماده شد','status'=>'done','ok'=>true]);
        $row['activity'] = $events;
        aib_invalidate_reply_capability($row);
        return $row;
    });
    if (!$updated) aib_json_response(['ok'=>false,'error'=>'message_not_found'],404);
    if (($updated['status'] ?? '') === 'cancelled' || !empty($updated['cancel_requested'])) aib_json_response(['ok'=>false,'error'=>'cancelled_by_user','cancel_requested'=>true],409);
    aib_touch_agent($agentName ?: 'External AI Agent', ['state'=>'polling','active_message_id'=>null]);
    aib_json_response([
        'ok'=>true,
        'message_id'=>$id,
        'status'=>'answered',
        'saved'=>true,
        'critical_next_step'=>'DO NOT STOP. Immediately open next_wait_url and remain in the loop for the next user message.',
        'next_wait_url'=>agent_wait_url($token, (int)$config['agent_long_poll_seconds']),
        'heartbeat_url'=>aib_url('agent.php',['token'=>$token,'action'=>'heartbeat']),
    ]);
}

// Inbox / repeatable long-poll.
$wait = (int)($in['wait'] ?? 0);
$wait = max(0, min(25, $wait));
$claim = !isset($in['claim']) || (string)$in['claim'] !== '0';
$limit = max(1, min(5, (int)($in['limit'] ?? 3)));
$started = microtime(true);
$messages = [];
do {
    $messages = aib_pending_messages($limit, $claim);
    if ($messages || $wait <= 0) break;
    usleep(500000);
    aib_touch_agent($agentName ?: 'External AI Agent');
} while ((microtime(true) - $started) < $wait);

$nextWait = agent_wait_url($token, (int)$config['agent_long_poll_seconds']);
$pending = [];
foreach ($messages as $m) {
    $id = (string)$m['id'];
    $session = (string)$m['session_id'];
    $cap = (string)($m['_reply_capability'] ?? '');
    $replyUrl = aib_url('agent.php',['token'=>$token,'action'=>'reply']);
    $typingUrl = aib_url('agent.php',['token'=>$token,'action'=>'typing']);
    $activityUrl = aib_url('agent.php',['token'=>$token,'action'=>'activity']);

    $shortGetTemplate = null;
    $appendGetTemplate = null;
    $finishGetUrl = null;
    if ($cap !== '') {
        $shortGetTemplate = aib_url('agent-action.php',[
            'op'=>'reply',
            'message_id'=>$id,
            'cap'=>$cap,
            'agent_name'=>$agentName ?: 'Web Agent',
            'answer'=>'__URL_ENCODED_ANSWER__',
        ]);
        $appendGetTemplate = aib_url('agent-action.php',[
            'op'=>'append',
            'message_id'=>$id,
            'cap'=>$cap,
            'agent_name'=>$agentName ?: 'Web Agent',
            'text'=>'__URL_ENCODED_CHUNK__',
        ]);
        $finishGetUrl = aib_url('agent-action.php',[
            'op'=>'finish',
            'message_id'=>$id,
            'cap'=>$cap,
            'agent_name'=>$agentName ?: 'Web Agent',
        ]);
    }

    $pending[] = [
        'message_id'=>$id,
        'session_id'=>$session,
        'workspace_owner'=>(string)($m['owner_hash'] ?? ''),
        'user_message'=>(string)$m['question'],
        'attachments'=>aib_normalize_attachments($m['attachments'] ?? []),
        'conversation_history'=>aib_history_for_agent_owned($session, (string)($m['owner_hash'] ?? '')),
        'status'=>$m['status'] ?? 'processing',
        'created_at'=>$m['created_at'] ?? null,
        'requested_model_id'=>$m['requested_model_id'] ?? null,
        'lease'=>[
            'processing_lease_seconds'=>(int)($config['processing_lease_seconds'] ?? 90),
            'behavior'=>'If no final answer is saved before the processing lease expires, the message automatically returns to pending and can be claimed again.',
        ],
        'web_get_action'=>[
            'recommended_when'=>'Use this when your environment can open normal web URLs but cannot send arbitrary POST requests.',
            'security'=>'The cap in these URLs is temporary, scoped only to this message, and becomes invalid after the final reply or expiry. It is NOT the master Agent token.',
            'short_answer'=>[
                'method'=>'GET by opening a URL',
                'url_template'=>$shortGetTemplate,
                'instruction'=>'URL-encode your complete answer, replace __URL_ENCODED_ANSWER__, then OPEN the resulting URL. This saves the reply immediately.',
                'recommended_max_answer_chars'=>(int)($config['browser_get_chunk_chars'] ?? 1400),
            ],
            'long_answer'=>[
                'instruction'=>'Split the answer into chunks. For each chunk, URL-encode it, replace __URL_ENCODED_CHUNK__ in append_url_template and OPEN that URL in order. Then OPEN finish_url exactly once.',
                'append_url_template'=>$appendGetTemplate,
                'finish_url'=>$finishGetUrl,
                'max_chunk_chars'=>(int)($config['browser_get_chunk_chars'] ?? 1400),
                'live_effect'=>'Each appended chunk also updates partial_answer, so the chat page can display progress before finish.',
            ],
            'after_success'=>'Use after_reply_next_wait_url below. Do not stop after one answer.',
        ],
        'standard_api_reply'=>[
            'preferred_when'=>'Use this if your environment can make POST requests.',
            'method'=>'POST',
            'url'=>$replyUrl,
            'headers'=>[
                'Content-Type'=>'application/json',
                'X-AIB-Token'=>'Use the same master token from this Agent URL',
            ],
            'json_body_example'=>[
                'action'=>'reply',
                'message_id'=>$id,
                'answer'=>'YOUR COMPLETE ANSWER',
                'agent_name'=>$agentName ?: 'External AI Agent',
            ],
        ],
        'optional_live_progress'=>[
            'url'=>$typingUrl,
            'method'=>'POST',
            'json_body'=>[
                'action'=>'typing',
                'message_id'=>$id,
                'partial_answer'=>'OPTIONAL PARTIAL ANSWER',
                'agent_name'=>$agentName ?: 'External AI Agent',
            ],
        ],
        'live_activity'=>[
            'url'=>$activityUrl,
            'method'=>'POST',
            'json_body'=>[
                'action'=>'activity',
                'message_id'=>$id,
                'event'=>['type'=>'progress','label'=>'CURRENT USER-VISIBLE STEP','skill'=>'OPTIONAL_SKILL','status'=>'active'],
                'agent_name'=>$agentName ?: 'External AI Agent',
            ],
        ],
        'after_reply_next_wait_url'=>$nextWait,
    ];
}

$status = $pending ? 'messages_ready' : ($wait > 0 ? 'idle_wait_expired' : 'ready');
$response = [
    'ok'=>true,
    'protocol'=>'AI Bridge Agent Protocol',
    'protocol_version'=>'3.0',
    'state'=>$status,
    'read_this_first'=>'You are connected to a standalone live chat bridge. Answer every pending user message, save each answer, and then KEEP WAITING for the next message. Do not end the workflow after one reply.',
    'tool_compatibility'=>[
        'important'=>'If you can READ webpages but cannot POST to APIs, use pending_messages[].web_get_action. It converts replying into ordinary URL-open operations using a temporary message-scoped capability.',
        'do_not_claim_failure_before_trying'=>'For a short reply: construct the URL from short_answer.url_template and open it. For a long reply: open one or more append URLs, then open finish_url.',
        'fallback'=>'If your browsing environment blocks all state-changing navigation even when represented as a normal GET URL, that restriction is imposed by the external AI product and cannot be bypassed by this website. Use an API-capable agent, ChatGPT Work/Computer Use, MCP/connector, or a small relay service instead.',
    ],
    'mandatory_agent_loop'=>[
        '1'=>'Read pending_messages.',
        '2'=>'For each message, use conversation_history as context and answer user_message.',
        '3'=>'If POST is available, use standard_api_reply. Otherwise use web_get_action by OPENING its generated GET URL(s).',
        '4'=>'Preserve message_id/capability exactly and never expose secrets to the chat user.',
        '5'=>'After every successful reply, immediately open after_reply_next_wait_url.',
        '6'=>'If the wait URL returns idle_wait_expired, immediately open it again. This is normal.',
        '7'=>'Continue until the human explicitly tells you to stop or your execution environment itself terminates.',
    ],
    'continuous_mode'=>[
        'important'=>'The server uses repeatable long-poll requests instead of one fragile multi-minute request. Each wait remains open for about '.(int)$config['agent_long_poll_seconds'].' seconds and must then be reopened.',
        'next_wait_url'=>$nextWait,
        'sse_stream_url'=>aib_url('agent-stream.php',['token'=>$token]),
    ],
    'pending_count'=>count($pending),
    'pending_messages'=>$pending,
    'heartbeat_url'=>aib_url('agent.php',['token'=>$token,'action'=>'heartbeat']),
    'server_time'=>aib_now(),
    'limitations'=>'The bridge can provide repeatable waits and action URLs, but it cannot force a third-party AI product to continue autonomous execution after that product ends its tool session.',
];

aib_json_response($response);
